# Generated by Django 4.1.3 on 2023-05-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="content_type",
            field=models.CharField(
                choices=[("Content", "Content"), ("Assignment", "Assignment")],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
