# Generated by Django 4.1.3 on 2023-05-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_management", "0002_file_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("Content", "Content"),
                    ("Assignment", "Assignment"),
                    ("Exam", "Exam"),
                ],
                default="Content",
                max_length=10,
            ),
        ),
    ]
