# Generated by Django 4.1.3 on 2023-05-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_management", "0003_alter_file_content_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="file",
            name="due_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
