# Generated by Django 4.1.3 on 2023-05-15 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("file_management", "0005_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="assignment_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment",
                to="file_management.file",
            ),
            preserve_default=False,
        ),
    ]
