# Generated by Django 4.1.3 on 2023-05-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Teacher", "Teacher"),
                    ("Student", "Student"),
                ],
                max_length=100,
            ),
        ),
    ]
