# Generated by Django 4.1.3 on 2023-05-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module", "0001_initial"),
        ("accounts", "0003_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="modules",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="module.module"
            ),
        ),
    ]
